// CYTrapBase.cpp - í´ë¼ì´ì–¸íŠ¸ ë©”ì‹œ ë™ê¸°í™” ê°œì„ 
#include "Items/CYTrapBase.h"
#include "Player/CYPlayerCharacter.h"
#include "AbilitySystemBlueprintLibrary.h"
#include "AbilitySystemComponent.h"
#include "TimerManager.h"
#include "Components/SphereComponent.h"
#include "Components/StaticMeshComponent.h"
#include "GAS/CYAttributeSet.h"
#include "GAS/CYGameplayEffects.h"
#include "CYGameplayTags.h"
#include "Kismet/GameplayStatics.h"
#include "Sound/SoundBase.h"
#include "Net/UnrealNetwork.h"

ACYTrapBase::ACYTrapBase()
{
    ItemName = FText::FromString("Base Trap");
    ItemDescription = FText::FromString("A base trap class");
    ItemTag = FGameplayTag::RequestGameplayTag("Item.Trap");

    MaxStackCount = 5;
    ItemCount = 1;
    TrapType = ETrapType::Slow;
    TrapState = ETrapState::MapPlaced;

    // âœ… ë„¤íŠ¸ì›Œí‚¹ ì„¤ì • ê°•í™”
    bReplicates = true;
    SetReplicateMovement(true);
    bAlwaysRelevant = true;

    // âœ… ê¸°ë³¸ ë©”ì‹œ ì„¤ì • ê°œì„ 
    if (ItemMesh)
    {
        static ConstructorHelpers::FObjectFinder<UStaticMesh> TrapMeshAsset(TEXT("/Engine/BasicShapes/Cylinder"));
        if (TrapMeshAsset.Succeeded())
        {
            ItemMesh->SetStaticMesh(TrapMeshAsset.Object);
            ItemMesh->SetWorldScale3D(FVector(0.5f, 0.5f, 0.1f));
        }
        
        // âœ… ê¸°ë³¸ ë©”ì‹œ ì„¤ì • ê°•í™”
        ItemMesh->SetCollisionEnabled(ECollisionEnabled::NoCollision);
        ItemMesh->SetVisibility(true);
        ItemMesh->SetHiddenInGame(false); // ëª…ì‹œì ìœ¼ë¡œ í‘œì‹œ
        ItemMesh->SetCastShadow(true); // ê·¸ë¦¼ì í™œì„±í™”
    }

    // ê¸°ë³¸ íŠ¸ë© ë°ì´í„° ì´ˆê¸°í™”
    TrapData.TrapType = TrapType;
    TrapData.TrapName = ItemName;
    TrapData.TrapDescription = ItemDescription;
    TrapData.TriggerRadius = TriggerRadius;
    TrapData.ArmingDelay = ArmingDelay;
    TrapData.TrapLifetime = TrapLifetime;
}

void ACYTrapBase::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const
{
    Super::GetLifetimeReplicatedProps(OutLifetimeProps);
    DOREPLIFETIME(ACYTrapBase, TrapState);
    DOREPLIFETIME(ACYTrapBase, bIsArmed);
    // âœ… TrapTypeë„ ë¦¬í”Œë¦¬ì¼€ì´íŠ¸í•˜ì—¬ í´ë¼ì´ì–¸íŠ¸ì—ì„œ ì˜¬ë°”ë¥¸ íƒ€ì… ì¸ì‹
    DOREPLIFETIME(ACYTrapBase, TrapType);
    DOREPLIFETIME(ACYTrapBase, TrapData);
}

void ACYTrapBase::BeginPlay()
{
    Super::BeginPlay();

    // âœ… ëª¨ë“  í´ë¼ì´ì–¸íŠ¸ì—ì„œ ìƒíƒœë³„ íŠ¸ë© ì„¤ì •
    SetupTrapForCurrentState();
    
    // âœ… ì„œë²„ì™€ í´ë¼ì´ì–¸íŠ¸ ëª¨ë‘ì—ì„œ ë¹„ì£¼ì–¼ ì„¤ì •
    SetupTrapVisuals();
    
    // âœ… ì„œë²„ì—ì„œë§Œ ë¡œì§ ì²˜ë¦¬
    if (HasAuthority())
    {
        OnTrapSpawned();
    }

    UE_LOG(LogTemp, Warning, TEXT("ğŸ¯ Trap BeginPlay: %s (State: %s, Authority: %s, CollisionEnabled: %s)"), 
           *ItemName.ToString(), 
           TrapState == ETrapState::MapPlaced ? TEXT("MapPlaced") : TEXT("PlayerPlaced"),
           HasAuthority() ? TEXT("Server") : TEXT("Client"),
           InteractionSphere ? (InteractionSphere->GetCollisionEnabled() != ECollisionEnabled::NoCollision ? TEXT("Enabled") : TEXT("Disabled")) : TEXT("NULL"));
}

void ACYTrapBase::SetupTrapForCurrentState()
{
    if (!InteractionSphere) return;

    if (TrapState == ETrapState::MapPlaced)
    {
        // âœ… ë§µ ë°°ì¹˜ ìƒíƒœ: í”½ì—… ê°€ëŠ¥í•˜ë„ë¡ ì„¤ì •
        InteractionSphere->SetSphereRadius(150.0f);
        InteractionSphere->SetCollisionEnabled(ECollisionEnabled::QueryOnly);
        InteractionSphere->SetCollisionResponseToAllChannels(ECR_Ignore);
        InteractionSphere->SetCollisionResponseToChannel(ECC_Pawn, ECR_Overlap);
        InteractionSphere->SetCollisionObjectType(ECC_WorldDynamic);
        
        // âœ… ì„œë²„ì—ì„œë§Œ í”½ì—… ë°”ì¸ë”©
        if (HasAuthority())
        {
            InteractionSphere->OnComponentBeginOverlap.Clear();
            InteractionSphere->OnComponentEndOverlap.Clear();
            InteractionSphere->OnComponentBeginOverlap.AddDynamic(this, &ACYTrapBase::OnPickupSphereOverlap);
            InteractionSphere->OnComponentEndOverlap.AddDynamic(this, &ACYTrapBase::OnPickupSphereEndOverlap);
        }
        
        UE_LOG(LogTemp, Warning, TEXT("ğŸ¯ Trap set as PICKUPABLE: %s (Radius: %f)"), 
               *ItemName.ToString(), InteractionSphere->GetScaledSphereRadius());
    }
    else if (TrapState == ETrapState::PlayerPlaced)
    {
        // âœ… í”Œë ˆì´ì–´ ë°°ì¹˜ ìƒíƒœ: íŠ¸ë¦¬ê±° ëª¨ë“œ
        if (HasAuthority())
        {
            SetupTrapTimers();
        }
        
        UE_LOG(LogTemp, Warning, TEXT("ğŸ¯ Trap set as ACTIVE: %s"), *ItemName.ToString());
    }
}

void ACYTrapBase::ConvertToPlayerPlacedTrap(AActor* PlacingPlayer)
{
    if (!HasAuthority()) return;

    TrapState = ETrapState::PlayerPlaced;
    SetOwner(PlacingPlayer);
    bIsPickedUp = true;
    
    SetupTrapForCurrentState();
    
    // âœ… í´ë¼ì´ì–¸íŠ¸ë“¤ì—ê²Œ ì¦‰ì‹œ ì‹œê°ì  ì—…ë°ì´íŠ¸ ì•Œë¦¼
    MulticastUpdateTrapVisuals();
    
    // âœ… ì¶”ê°€: ë„¤íŠ¸ì›Œí¬ ì—…ë°ì´íŠ¸ ê°•ì œ ì‹¤í–‰
    ForceNetUpdate();
    
    UE_LOG(LogTemp, Warning, TEXT("ğŸ¯ Trap converted to PlayerPlaced by %s"), 
           PlacingPlayer ? *PlacingPlayer->GetName() : TEXT("Unknown"));
}

void ACYTrapBase::SetupTrapTimers()
{
    if (TrapState != ETrapState::PlayerPlaced) return;

    GetWorld()->GetTimerManager().SetTimer(ArmingTimer, this, &ACYTrapBase::ArmTrap, 
                                          TrapData.ArmingDelay, false);
    
    GetWorld()->GetTimerManager().SetTimer(LifetimeTimer, [this]()
    {
        Destroy();
    }, TrapData.TrapLifetime, false);
}

void ACYTrapBase::ArmTrap()
{
    if (!HasAuthority() || TrapState != ETrapState::PlayerPlaced) return;

    bIsArmed = true;

    if (InteractionSphere)
    {
        InteractionSphere->SetSphereRadius(TrapData.TriggerRadius);
        InteractionSphere->SetCollisionEnabled(ECollisionEnabled::QueryOnly);
        InteractionSphere->SetCollisionResponseToAllChannels(ECR_Ignore);
        InteractionSphere->SetCollisionResponseToChannel(ECC_Pawn, ECR_Overlap);
        
        InteractionSphere->OnComponentBeginOverlap.Clear();
        InteractionSphere->OnComponentEndOverlap.Clear();
        InteractionSphere->OnComponentBeginOverlap.AddDynamic(this, &ACYTrapBase::OnTriggerSphereOverlap);
    }

    ForceNetUpdate();
    OnTrapArmed();

    UE_LOG(LogTemp, Log, TEXT("âœ… Trap armed and ready: %s"), *ItemName.ToString());
}

void ACYTrapBase::OnTriggerSphereOverlap(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor,
        UPrimitiveComponent* OtherComp, int32 OtherBodyIndex,
        bool bFromSweep, const FHitResult& SweepResult)
{
    if (TrapState != ETrapState::PlayerPlaced || !bIsArmed || !HasAuthority()) return;

    if (OtherActor == GetOwner())
    {
        UE_LOG(LogTemp, Log, TEXT("ğŸš« Trap owner stepped on own trap - ignoring"));
        return;
    }

    ACYPlayerCharacter* Target = Cast<ACYPlayerCharacter>(OtherActor);
    if (!Target) return;

    UE_LOG(LogTemp, Warning, TEXT("ğŸ’¥ TRAP TRIGGERED! %s stepped on %s's trap"), 
           *Target->GetName(), 
           GetOwner() ? *GetOwner()->GetName() : TEXT("Unknown"));

    OnTrapTriggered(Target);
    ApplyTrapEffects(Target);
    MulticastOnTrapTriggered(Target);
    
    Destroy();
}

// âœ… ìƒˆë¡œìš´ ë©€í‹°ìºìŠ¤íŠ¸ í•¨ìˆ˜ - ì‹œê°ì  ì—…ë°ì´íŠ¸
void ACYTrapBase::MulticastUpdateTrapVisuals_Implementation()
{
    UE_LOG(LogTemp, Warning, TEXT("ğŸ¨ MulticastUpdateTrapVisuals called on %s"), 
           HasAuthority() ? TEXT("Server") : TEXT("Client"));
    
    // âœ… í´ë¼ì´ì–¸íŠ¸ì—ì„œë„ ê°•ì œë¡œ ì‹œê°ì  ì„¤ì •
    SetupTrapVisuals();
    
    // âœ… ë©”ì‹œ ê°€ì‹œì„± ê°•ì œ ì„¤ì •
    if (ItemMesh)
    {
        ItemMesh->SetVisibility(true);
        ItemMesh->SetHiddenInGame(false);
        ItemMesh->MarkRenderStateDirty();
        
        UE_LOG(LogTemp, Warning, TEXT("ğŸ¨ Client mesh visibility forced: %s"), 
               ItemMesh->IsVisible() ? TEXT("true") : TEXT("false"));
    }
}

void ACYTrapBase::MulticastOnTrapTriggered_Implementation(ACYPlayerCharacter* Target)
{
    if (!HasAuthority()) // í´ë¼ì´ì–¸íŠ¸ì—ì„œë§Œ ì‹¤í–‰
    {
        OnTrapTriggered(Target);
        SetupTrapVisuals(); // íŠ¸ë¦¬ê±° ì‹œê° íš¨ê³¼
    }
}

void ACYTrapBase::OnPickupSphereOverlap(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor,
    UPrimitiveComponent* OtherComp, int32 OtherBodyIndex,
    bool bFromSweep, const FHitResult& SweepResult)
{
    OnSphereOverlap(OverlappedComponent, OtherActor, OtherComp, OtherBodyIndex, bFromSweep, SweepResult);
}

void ACYTrapBase::OnPickupSphereEndOverlap(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor,
    UPrimitiveComponent* OtherComp, int32 OtherBodyIndex)
{
    OnSphereEndOverlap(OverlappedComponent, OtherActor, OtherComp, OtherBodyIndex);
}

void ACYTrapBase::EndPlay(const EEndPlayReason::Type EndPlayReason)
{
    OnTrapDestroyed();
    Super::EndPlay(EndPlayReason);
}

void ACYTrapBase::OnTrapSpawned_Implementation()
{
    UE_LOG(LogTemp, Log, TEXT("ğŸ”§ Base trap spawned"));
}

void ACYTrapBase::OnTrapArmed_Implementation()
{
    UE_LOG(LogTemp, Warning, TEXT("âš¡ Base trap armed"));
    PlayTrapSound();
}

void ACYTrapBase::OnTrapTriggered_Implementation(ACYPlayerCharacter* Target)
{
    if (Target)
    {
        UE_LOG(LogTemp, Warning, TEXT("ğŸ’¥ Base trap triggered on %s"), *Target->GetName());
    }
}

void ACYTrapBase::OnTrapDestroyed_Implementation()
{
    UE_LOG(LogTemp, Log, TEXT("ğŸ—‘ï¸ Base trap destroyed"));
}

void ACYTrapBase::SetupTrapVisuals_Implementation()
{
    UE_LOG(LogTemp, Warning, TEXT("ğŸ¨ SetupTrapVisuals called on %s"), 
           HasAuthority() ? TEXT("Server") : TEXT("Client"));

    if (ItemMesh)
    {
        // âœ… ê¸°ë³¸ ë©”ì‹œê°€ ì—†ìœ¼ë©´ ì„¤ì •
        if (!ItemMesh->GetStaticMesh())
        {
            static ConstructorHelpers::FObjectFinder<UStaticMesh> DefaultMesh(TEXT("/Engine/BasicShapes/Cylinder"));
            if (DefaultMesh.Succeeded())
            {
                ItemMesh->SetStaticMesh(DefaultMesh.Object);
                UE_LOG(LogTemp, Warning, TEXT("ğŸ¨ Set default cylinder mesh"));
            }
        }
        
        // âœ… TrapDataì—ì„œ ë©”ì‹œê°€ ìˆìœ¼ë©´ ì‚¬ìš©
        if (TrapData.TrapMesh)
        {
            ItemMesh->SetStaticMesh(TrapData.TrapMesh);
            UE_LOG(LogTemp, Warning, TEXT("ğŸ¨ Set TrapData mesh: %s"), *TrapData.TrapMesh->GetName());
        }
        
        // âœ… ê¸°ë³¸ ìŠ¤ì¼€ì¼ ë³´ì¥
        FVector CurrentScale = ItemMesh->GetComponentScale();
        if (CurrentScale.IsNearlyZero())
        {
            ItemMesh->SetWorldScale3D(FVector(0.5f, 0.5f, 0.1f));
        }
        
        // âœ… ê°€ì‹œì„± ê°•ì œ ë³´ì¥
        ItemMesh->SetVisibility(true);
        ItemMesh->SetHiddenInGame(false);
        ItemMesh->SetCastShadow(true);
        
        // âœ… ë Œë” ìƒíƒœ ì—…ë°ì´íŠ¸ ê°•ì œ
        ItemMesh->MarkRenderStateDirty();
        
        // âœ… ë¨¸í‹°ë¦¬ì–¼ ì„¤ì • ê°œì„  - ì¤‘ë³µ ìƒì„± ë°©ì§€
        UMaterialInterface* Material = ItemMesh->GetMaterial(0);
        if (Material && !Material->IsA<UMaterialInstanceDynamic>())
        {
            UMaterialInstanceDynamic* DynamicMaterial = UMaterialInstanceDynamic::Create(Material, this);
            if (DynamicMaterial)
            {
                DynamicMaterial->SetVectorParameterValue(TEXT("BaseColor"), TrapData.TrapColor);
                ItemMesh->SetMaterial(0, DynamicMaterial);
                
                UE_LOG(LogTemp, Warning, TEXT("ğŸ¨ Applied dynamic material with color %s"), 
                       *TrapData.TrapColor.ToString());
            }
        }
        else if (!Material)
        {
            // âœ… ë¨¸í‹°ë¦¬ì–¼ì´ ì—†ìœ¼ë©´ ê¸°ë³¸ ë¨¸í‹°ë¦¬ì–¼ ìƒì„±
            UMaterialInterface* DefaultMat = UMaterial::GetDefaultMaterial(MD_Surface);
            if (DefaultMat)
            {
                UMaterialInstanceDynamic* DefaultMaterial = UMaterialInstanceDynamic::Create(DefaultMat, this);
                if (DefaultMaterial)
                {
                    DefaultMaterial->SetVectorParameterValue(TEXT("BaseColor"), TrapData.TrapColor);
                    ItemMesh->SetMaterial(0, DefaultMaterial);
                    
                    UE_LOG(LogTemp, Warning, TEXT("ğŸ¨ Created default material with color %s"), 
                           *TrapData.TrapColor.ToString());
                }
            }
        }
        
        UE_LOG(LogTemp, Warning, TEXT("ğŸ¨ Trap visuals setup complete: Mesh=%s, Scale=%s, Visible=%s, Hidden=%s"), 
               ItemMesh->GetStaticMesh() ? *ItemMesh->GetStaticMesh()->GetName() : TEXT("NULL"),
               *ItemMesh->GetComponentScale().ToString(),
               ItemMesh->IsVisible() ? TEXT("true") : TEXT("false"),
               ItemMesh->bHiddenInGame ? TEXT("true") : TEXT("false"));
    }
    else
    {
        UE_LOG(LogTemp, Error, TEXT("âŒ ItemMesh is NULL in SetupTrapVisuals"));
    }
}

void ACYTrapBase::PlayTrapSound_Implementation()
{
    if (TrapData.TriggerSound)
    {
        UGameplayStatics::PlaySoundAtLocation(GetWorld(), TrapData.TriggerSound, GetActorLocation());
    }
}

void ACYTrapBase::ApplyCustomEffects_Implementation(ACYPlayerCharacter* Target)
{
    UE_LOG(LogTemp, Log, TEXT("ğŸ¯ Applying base custom effects"));
}

void ACYTrapBase::ApplyTrapEffects(ACYPlayerCharacter* Target)
{
    if (!Target) return;

    UAbilitySystemComponent* TargetASC = Target->GetAbilitySystemComponent();
    if (!TargetASC) return;

    UE_LOG(LogTemp, Warning, TEXT("ğŸ¯ Applying trap effects to %s"), *Target->GetName());

    for (TSubclassOf<UGameplayEffect> EffectClass : TrapData.GameplayEffects)
    {
        if (EffectClass)
        {
            ApplySingleEffect(TargetASC, EffectClass);
        }
    }

    for (TSubclassOf<UGameplayEffect> EffectClass : ItemEffects)
    {
        if (EffectClass)
        {
            ApplySingleEffect(TargetASC, EffectClass);
        }
    }

    ApplyCustomEffects(Target);

    UE_LOG(LogTemp, Log, TEXT("âœ… Applied %d trap effects"), 
           TrapData.GameplayEffects.Num() + ItemEffects.Num());
}

void ACYTrapBase::ApplySingleEffect(UAbilitySystemComponent* TargetASC, TSubclassOf<UGameplayEffect> EffectClass)
{
    if (!TargetASC || !EffectClass) return;

    FGameplayEffectContextHandle EffectContext = TargetASC->MakeEffectContext();
    EffectContext.AddSourceObject(this);
    
    FGameplayEffectSpecHandle EffectSpec = TargetASC->MakeOutgoingSpec(EffectClass, 1, EffectContext);
    if (EffectSpec.IsValid())
    {
        TargetASC->ApplyGameplayEffectSpecToSelf(*EffectSpec.Data.Get());
        UE_LOG(LogTemp, Log, TEXT("Applied effect: %s"), *EffectClass->GetName());
    }
}