// CYPlayerCharacter.cpp - ì–´ë¹Œë¦¬í‹° ì¤‘ë³µ ë“±ë¡ ë°©ì§€
#include "Player/CYPlayerCharacter.h"
#include "Camera/CameraComponent.h"
#include "GameFramework/SpringArmComponent.h"
#include "GameFramework/CharacterMovementComponent.h"
#include "Components/CapsuleComponent.h"
#include "GAS/CYAbilitySystemComponent.h"
#include "GAS/CYAttributeSet.h"
#include "GAS/CYGameplayEffects.h"
#include "Components/CYInventoryComponent.h"
#include "Components/CYItemInteractionComponent.h"
#include "Components/CYWeaponComponent.h"
#include "CYGameplayTags.h"
#include "Abilities/GA_WeaponAttack.h"
#include "Abilities/GA_PlaceTrap.h"
#include "Net/UnrealNetwork.h"

ACYPlayerCharacter::ACYPlayerCharacter()
{
    PrimaryActorTick.bCanEverTick = false;
    bReplicates = true;

    // ê¸°ë³¸ ì„¤ì •
    GetCapsuleComponent()->InitCapsuleSize(42.f, 96.0f);
    bUseControllerRotationPitch = false;
    bUseControllerRotationYaw = false;
    bUseControllerRotationRoll = false;

    // ìºë¦­í„° ì´ë™ ì„¤ì •
    GetCharacterMovement()->bOrientRotationToMovement = true;
    GetCharacterMovement()->RotationRate = FRotator(0.0f, 500.0f, 0.0f);
    GetCharacterMovement()->JumpZVelocity = 700.f;
    GetCharacterMovement()->AirControl = 0.35f;
    GetCharacterMovement()->MaxWalkSpeed = 500.f;
    GetCharacterMovement()->MinAnalogWalkSpeed = 20.f;
    GetCharacterMovement()->BrakingDecelerationWalking = 2000.f;

    // ì¹´ë©”ë¼ ì‹œìŠ¤í…œ
    SpringArmComponent = CreateDefaultSubobject<USpringArmComponent>(TEXT("SpringArm"));
    SpringArmComponent->SetupAttachment(RootComponent);
    SpringArmComponent->TargetArmLength = 400.0f;
    SpringArmComponent->bUsePawnControlRotation = true;

    CameraComponent = CreateDefaultSubobject<UCameraComponent>(TEXT("Camera"));
    CameraComponent->SetupAttachment(SpringArmComponent, USpringArmComponent::SocketName);
    CameraComponent->bUsePawnControlRotation = false;

    // GAS ì‹œìŠ¤í…œ
    AbilitySystemComponent = CreateDefaultSubobject<UCYAbilitySystemComponent>(TEXT("AbilitySystemComponent"));
    AbilitySystemComponent->SetIsReplicated(true);
    AttributeSet = CreateDefaultSubobject<UCYAttributeSet>(TEXT("AttributeSet"));

    // ê²Œì„í”Œë ˆì´ ì»´í¬ë„ŒíŠ¸ë“¤
    InventoryComponent = CreateDefaultSubobject<UCYInventoryComponent>(TEXT("InventoryComponent"));
    ItemInteractionComponent = CreateDefaultSubobject<UCYItemInteractionComponent>(TEXT("ItemInteractionComponent"));
    WeaponComponent = CreateDefaultSubobject<UCYWeaponComponent>(TEXT("WeaponComponent"));

    // âœ… ê¸°ë³¸ ì–´ë¹Œë¦¬í‹° - ê°ê° í•œ ë²ˆë§Œ ë“±ë¡
    DefaultAbilities.Add(UGA_WeaponAttack::StaticClass());
    DefaultAbilities.Add(UGA_PlaceTrap::StaticClass());
    
    // âœ… ì¤‘ë³µ ë°©ì§€ë¥¼ ìœ„í•œ í”Œë˜ê·¸
    bAbilitiesGranted = false;
}

void ACYPlayerCharacter::BeginPlay()
{
    Super::BeginPlay();
    
    if (HasAuthority())
    {
        InitializeAbilitySystem();
    }
}

void ACYPlayerCharacter::SetupPlayerInputComponent(UInputComponent* PlayerInputComponent)
{
    Super::SetupPlayerInputComponent(PlayerInputComponent);
}

void ACYPlayerCharacter::PossessedBy(AController* NewController)
{
    Super::PossessedBy(NewController);
    
    if (HasAuthority())
    {
        InitializeAbilitySystem();
    }
}

void ACYPlayerCharacter::OnRep_PlayerState()
{
    Super::OnRep_PlayerState();
    InitializeAbilitySystem();
}

void ACYPlayerCharacter::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const
{
    Super::GetLifetimeReplicatedProps(OutLifetimeProps);
    DOREPLIFETIME(ACYPlayerCharacter, bAbilitiesGranted); // âœ… ì–´ë¹Œë¦¬í‹° ë¶€ì—¬ ìƒíƒœ ë™ê¸°í™”
}

UAbilitySystemComponent* ACYPlayerCharacter::GetAbilitySystemComponent() const
{
    return AbilitySystemComponent;
}

// ============ ì…ë ¥ ì²˜ë¦¬ í•¨ìˆ˜ë“¤ ============

void ACYPlayerCharacter::Move(const FVector2D& Value)
{
    if (Controller != nullptr && !Value.IsZero())
    {
        const FRotator Rotation = Controller->GetControlRotation();
        const FRotator YawRotation(0, Rotation.Yaw, 0);

        const FVector ForwardDirection = FRotationMatrix(YawRotation).GetUnitAxis(EAxis::X);
        const FVector RightDirection = FRotationMatrix(YawRotation).GetUnitAxis(EAxis::Y);

        AddMovementInput(ForwardDirection, Value.Y);
        AddMovementInput(RightDirection, Value.X);
    }
}

void ACYPlayerCharacter::Look(const FVector2D& Value)
{
    if (Controller != nullptr && !Value.IsZero())
    {
        AddControllerYawInput(Value.X);
        AddControllerPitchInput(Value.Y);
    }
}

void ACYPlayerCharacter::InteractPressed()
{
    if (ItemInteractionComponent)
    {
        ItemInteractionComponent->InteractWithNearbyItem();
    }
}

void ACYPlayerCharacter::AttackPressed()
{
    if (WeaponComponent)
    {
        WeaponComponent->PerformAttack();
    }
}

void ACYPlayerCharacter::UseInventorySlot(int32 SlotIndex)
{
    if (InventoryComponent)
    {
        InventoryComponent->UseItem(SlotIndex);
    }
}

// ============ GAS ì´ˆê¸°í™” ============

void ACYPlayerCharacter::InitializeAbilitySystem()
{
    if (!AbilitySystemComponent) return;

    AbilitySystemComponent->InitAbilityActorInfo(this, this);

    if (HasAuthority() && !bAbilitiesGranted)
    {
        GrantDefaultAbilities();
        ApplyInitialStats();
        bAbilitiesGranted = true; // âœ… ì¤‘ë³µ ë°©ì§€ í”Œë˜ê·¸ ì„¤ì •
        UE_LOG(LogTemp, Warning, TEXT("âœ… Abilities granted to: %s"), *GetName());
    }
}

void ACYPlayerCharacter::GrantDefaultAbilities()
{
    if (!AbilitySystemComponent || !HasAuthority() || bAbilitiesGranted) return;

    UE_LOG(LogTemp, Warning, TEXT("ğŸ¯ Granting %d default abilities to: %s"), DefaultAbilities.Num(), *GetName());

    for (int32 i = 0; i < DefaultAbilities.Num(); ++i)
    {
        TSubclassOf<UGameplayAbility>& AbilityClass = DefaultAbilities[i];
        if (AbilityClass)
        {
            // âœ… ì¤‘ë³µ ë“±ë¡ ë°©ì§€ - í•´ë‹¹ íƒœê·¸ì˜ ì–´ë¹Œë¦¬í‹°ê°€ ì´ë¯¸ ìˆëŠ”ì§€ ì²´í¬
            FGameplayTag AbilityTag;
            
            // ì–´ë¹Œë¦¬í‹° í´ë˜ìŠ¤ì— ë”°ë¼ íƒœê·¸ ê²°ì •
            if (AbilityClass == UGA_WeaponAttack::StaticClass())
            {
                AbilityTag = FGameplayTag::RequestGameplayTag("Ability.Weapon.Attack");
            }
            else if (AbilityClass == UGA_PlaceTrap::StaticClass())
            {
                AbilityTag = FGameplayTag::RequestGameplayTag("Ability.Trap.Place");
            }
            
            // í•´ë‹¹ íƒœê·¸ì˜ ì–´ë¹Œë¦¬í‹°ê°€ ì´ë¯¸ ìˆëŠ”ì§€ ì²´í¬
            if (AbilityTag.IsValid())
            {
                FGameplayTagContainer TagContainer;
                TagContainer.AddTag(AbilityTag);
                
                TArray<FGameplayAbilitySpec*> ExistingAbilities;
                AbilitySystemComponent->GetActivatableGameplayAbilitySpecsByAllMatchingTags(TagContainer, ExistingAbilities);
                
                if (ExistingAbilities.Num() > 0)
                {
                    UE_LOG(LogTemp, Warning, TEXT("âš ï¸ Ability already exists for tag: %s, skipping"), *AbilityTag.ToString());
                    continue;
                }
            }
            
            FGameplayAbilitySpec AbilitySpec(AbilityClass, 1, INDEX_NONE, this);
            FGameplayAbilitySpecHandle Handle = AbilitySystemComponent->GiveAbility(AbilitySpec);
            
            UE_LOG(LogTemp, Warning, TEXT("âœ… Granted ability: %s (Tag: %s)"), 
                   *AbilityClass->GetName(), 
                   AbilityTag.IsValid() ? *AbilityTag.ToString() : TEXT("None"));
        }
    }
}

void ACYPlayerCharacter::ApplyInitialStats()
{
    if (!AbilitySystemComponent || !HasAuthority()) return;

    FGameplayEffectContextHandle EffectContext = AbilitySystemComponent->MakeEffectContext();
    EffectContext.AddSourceObject(this);
    
    FGameplayEffectSpecHandle SpecHandle = AbilitySystemComponent->MakeOutgoingSpec(
        UGE_InitialStats::StaticClass(), 1, EffectContext);
    
    if (SpecHandle.IsValid())
    {
        AbilitySystemComponent->ApplyGameplayEffectSpecToSelf(*SpecHandle.Data.Get());
    }
}